export const GET_CONTAINER_RECEPIT = 'GET_CONTAINER_RECEPIT';
export const POST_CONTAINER_RECEPIT = 'POST_CONTAINER_RECEPIT';
export const DELETE_CONTAINER_RECEPIT = 'DELETE_CONTAINER_RECEPIT';
export const UPDATE_CONTAINER_RECEPIT_STATE = 'UPDATE_CONTAINER_RECEPIT_STATE';



