export const GET_SALE_RECORD = 'GET_SALE_RECORD';
export const GET_SELECT_SALE_RECORD = 'GET_SELECT_SALE_RECORD';
export const POST_SALE_RECORD = 'POST_SALE_RECORD';
export const PUT_SALE_RECORD = 'PUT_SALE_RECORD';
export const DELETE_SALE_RECORD = 'DELETE_SALE_RECORD';
export const UPDATE_SALE_RECORD_STATE = 'UPDATE_SALE_RECORD_STATE';