export const GET_MONEY_RECEPIT = 'GET_MONEY_RECEPIT';
export const POST_MONEY_RECEPIT = 'POST_MONEY_RECEPIT';
export const PUT_MONEY_RECEPIT = 'PUT_MONEY_RECEPIT';
export const DELETE_MONEY_RECEPIT = 'DELETE_MONEY_RECEPIT';
export const UPDATE_MONEY_RECEPIT = 'UPDATE_MONEY_RECEPIT';