export const GET_BUSINESS_ENTITY = 'GET_BUSINESS_ENTITY';
export const POST_BUSINESS_ENTITY = 'POST_BUSINESS_ENTITY';
export const PUT_BUSINESS_ENTITY = 'PUT_BUSINESS_ENTITY';
export const DELETE_BUSINESS_ENTITY = 'DELETE_BUSINESS_ENTITY';
export const UPDATE_STATE_BUSINESS_ENTITY = 'UPDATE_STATE_BUSINESS_ENTITY';