export const GET_VEGETABLES = 'GET_VEGETABLES';
export const POST_VEGETABLES = 'POST_VEGETABLES';
export const PUT_VEGETABLES = 'PUT_VEGETABLES';
export const DELETE_VEGETABLES = 'DELETE_VEGETABLES';
export const UPDATE_STATE_VEGETABLES = 'UPDATE_STATE_VEGETABLES';