export const GET_CONTAINER_RETURN = 'GET_CONTAINER_RETURN';
export const POST_CONTAINER_RETURN = 'POST_CONTAINER_RETURN';
export const DELETE_CONTAINER_RETURN = 'DELETE_CONTAINER_RETURN';
export const UPDATE_CONTAINER_RETURN_STATE = 'UPDATE_CONTAINER_RETURN_STATE';



