export const GET_ACCOUNT_GROUPS = 'GET_ACCOUNT_GROUPS';
export const POST_ACCOUNT_GROUPS = 'POST_ACCOUNT_GROUPS';
export const PUT_ACCOUNT_GROUPS = 'PUT_POST_ACCOUNT_GROUPS';
export const DELETE_ACCOUNT_GROUPS = 'DELETE_ACCOUNT_GROUPS';
export const UPDATE_STATE_ACCOUNT_GROUPS = 'UPDATE_STATE_ACCOUNT_GROUPS';
