export const GET_CUSTOMER_GROUPS = 'GET_CUSTOMER_GROUPS';
export const POST_CUSTOMER_GROUPS = 'POST_CUSTOMER_GROUPS';
export const PUT_CUSTOMER_GROUPS = 'PUT_CUSTOMER_GROUPS';
export const DELETE_CUSTOMER_GROUPS = 'DELETE_CUSTOMER_GROUPS';
export const UPDATE_STATE_CUSTOMER_GROUPS = 'UPDATE_STATE_CUSTOMER_GROUPS';